site_name: Flare Docs
site_description: Documentation of the FlareUI framework
site_author: maxus
repo_url: https://github.com/Maxuss/Flare
repo_name: Maxuss/Flare

nav:
  - index.md
  - setup.md
  - basic.md
  - ui/overview.md

plugins:
  - search
  - social:
      cards_layout_options:
        font_family: Inter

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables
  - def_list

extra_css:
  - stylesheets/extra.css

theme:
  features:
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  homepage: https://flare.maxus.space
  language: en
  font:
    text: Roboto
    code: JetBrains Mono
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to light theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/brightness-3
        name: Switch to dark theme