/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 */

val nmsVersions = arrayOf("v1_19_R3", "v1_19_R2", "v1_19_R1")

include(":flare:core")
include(":flare:common")
include(":flare:nms")
nmsVersions.forEach {
    include(":flare:nms:$it")
}

include(":test-plugin")